### ISSUE TITLE
Zero-length file generates non-helpful message

### ISSUE THREAD

**Issue by BurtHarris** [aviv1ron1/hash-cmd#1]
Repro case on Windows10:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Burt_> dir .\Sti_Trace.log


    Directory: C:\Users\Burt_


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/29/2016   3:11 PM              0 Sti_Trace.log


PS C:\Users\Burt_> hash md5 -i .\Sti_Trace.log
C:\ProgramData\nvm\v8.11.1\node_modules\hash-cmd\hash.js:34
                if (data.length > 0 && data[0] != '') {
                         ^

TypeError: Cannot read property 'length' of undefined
    at C:\ProgramData\nvm\v8.11.1\node_modules\hash-cmd\hash.js:34:26
    at Command.program.description.option.option.arguments.action (C:\ProgramData\nvm\v8.11.1\node_modules\hash-cmd\hash.js:70:22)
    at Command.listener (C:\ProgramData\nvm\v8.11.1\node_modules\hash-cmd\node_modules\commander\index.js:315:8)
    at emitOne (events.js:116:13)
    at Command.emit (events.js:211:7)
    at Command.parseArgs (C:\ProgramData\nvm\v8.11.1\node_modules\hash-cmd\node_modules\commander\index.js:653:12)
    at Command.parse (C:\ProgramData\nvm\v8.11.1\node_modules\hash-cmd\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\ProgramData\nvm\v8.11.1\node_modules\hash-cmd\hash.js:81:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
PS C:\Users\Burt_>
```

**Comment by aviv1ron1** [comment]
good idea. thanks @BurtHarris

**Comment by BurtHarris** [comment]
Happy to help.
